"""empty message

Revision ID: 3ff80e20d87d
Revises: 50f0ee5fa12a
Create Date: 2024-02-08 11:53:44.364042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff80e20d87d'
down_revision = '50f0ee5fa12a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
